### ISSUE TITLE
How the stat and P-value are calculated for each function?

### ISSUE THREAD

**Issue by koo-ec** [cdowd/twosamples#10]
I would like to know the stat and P-value are calculated inside each distance function? Is there any reference for their validity?

**Comment by cdowd** [comment]
The fullest description, with a proof of validity and an outline for a proof of consistency is available on [arXiv](https://arxiv.org/abs/2007.01360). 

Broadly, under the Null that the two distributions are the same, we can bootstrap samples with the same sizes from the joint distribution. Each resampling lets us calculate the test statistic again -- generating the distribution of test statistics under the null. Then the observed test statistic is compared to the null distribution, and the p-value is the portion of the null distribution that our observed test statistic is smaller than.

**Comment by koo-ec** [comment]
Thanks for your explanation. Do you have any sample example code for p-Value calculation? Something like the one that you have presented for each test. I read many papers regarding the EDF statistics for goodness of fit, but I really and deeply understand it from your sample codes.

**Comment by cdowd** [comment]
I would suggest looking at the code in “permutation_test_builder”.

That function takes any function calculating a test statistic as an input and returns a function that calculates a pvalue as output. All the test calculations in the package build up from test statistic functions using “permutation_test_builder”.

Alternately, you could just look at the code internal to ks_test or dts_test on your computer. As I mention above, they’re built with the test builder function, but they may be simpler to understand.

As a last addendum, in order to reduce memory usage, I don’t save the resampled test statistics anywhere, I merely add 1 to the “bigger” variable any time the resampled stat is larger than the observed stat. This lets me calculate the proportion that are larger with ease. 

Best
Connor
Koorosh Aslansefat <notifications@github.com> wrote:
“Thanks for your explanation. Do you have any sample example code for p-Value calculation? Something like the one that you have presented for each test. I read many papers regarding the EDF statistics for goodness of fit, but I really and deeply understand it from your sample codes.”

**Comment by koo-ec** [comment]
Thanks for your kind and valuable reply. I have tested it using the following code:

`library(twosamples)

a = rnorm(20, mean = 0, sd = 2)
b = rnorm(20, mean = 1, sd = 2)

ks_test(a,b)

nboots = 2000
t = ks_test(a,b)			
na = length(a)								
nb = length(b)
n = nb+na 				
comb = c(a,b)									
nboots = as.integer(nboots)				
reps = bigger = 0L							 
    while (reps < nboots) {						
      e = sample.int(n,na,T)
      f = sample.int(n,nb,T)
      boot_t = ks_test(comb[e],comb[f]) 
      if(boot_t >= t) bigger = 1L+bigger
      reps = 1L+reps
    }
    out = bigger/nboots
out`

It seems that is works well. However, my concern is that the result is different from MATLAB Code. When I run kstest2 in MATLAB, the p-value is different (I got p-value as "6.361457032740026e-08").

Do you know why it is happening?

**Comment by cdowd** [comment]
There are a few possible reasons. 

The first, and simplest, is that the sample you ran in R may be different than in matlab. As the p-value is a random variable which is a function of the observations, by randomly sampling for the vectors a and b, I would expect the p-value to change every time you ran that code -- even within R.

The second possible reason is that because the code here is based on a randomization routine to find the null distribution, even running it with the same samples twice, we should expect some small changes in the p-value. 

The third reason I would guess is that the matlab code probably uses the asymptotic distribution of the ks statistic to calculate the p-value. This is fairly standard across other ks_test code. However, I do not do that in this package because the asymptotic approximation is well known to be very conservative in small to medium samples. By using a randomization routine, I can ensure that the test size is the nominal size under the null. Thus, between this code and most ks_test code, I would expect small differences in the p-values, generally with this code having smaller p-values because it is not conservatively sized, but properly sized. 

As a final comment, if you haven't redefined `ks_test`, then I think your code is slightly off. For all the `ks_test` function calls except the first one, I think you should be using `ks_stat`. I don't think this will cause any errors, but the way you've coded it should cause it to be much slower, and cause the warning "the condition has length > 1 and only the first element will be used" to be thrown every time through the for loop. Essentially you're running a full bootstrap every time you run `ks_test`, but you've also run that on the interior of a bootstrap. Specifically, I would change it to:

```R
  nboots = 2000
  t = ks_stat(a,b)
  na = length(a)
  nb = length(b)
  n = nb+na
  comb = c(a,b)
  nboots = as.integer(nboots)
  reps = bigger = 0L
  while (reps < nboots) {
      e = sample.int(n,na,T)
      f = sample.int(n,nb,T)
      boot_t = ks_stat(comb[e],comb[f])
      if(boot_t >= t) bigger = 1L+bigger
      reps = 1L+reps
  }
  out = bigger/nboots
  out
```

**Comment by koo-ec** [comment]
I really appreciate your help. Thank you so much.

I think I can understand your codes and approach better now.

**Comment by cdowd** [comment]
I'm happy to have been of assistance.
