### ISSUE TITLE
Anderson Darling and DTS Weights?

### ISSUE THREAD

**Issue by manorman5** [cdowd/twosamples#11]
Hi,

Hope all is well. I've found this package and its accompanying paper incredibly helpful, thank you. I implemented your ideas in some python code to avoid hoping into R just to perform these tests. I'm confused by how you construct weights for the Anderson Darling and DTS distance metrics. From my point of view, all your written work suggests the weights for both statistics should be: `(Gcur*(1-Gcur))`. Instead you are using the following weight: `(n*Gcur*(1-Gcur))**0.5`. I haven't thought through or tested if the difference matters. I'm curious though why the difference exists. I would love to hear your reasoning, no worries if you don't have the time. 

Thanks!

**Comment by cdowd** [comment]
I'm glad to hear you've found it helpful! Hopefully, that will continue to be the case. 

If you don't mind sharing your python code, I'd be interested in it. But that is perhaps for another time.

You're right; there is an error in the documentation there, as well as a coding error. I'll explain everything I can, and then if you don't mind, I'll leave this issue open until I can find some time to fix the docs and code, as I don't believe there are any _critical_ issues. 

My comments below will start from the beginning, proving the variance of the difference of ECDFs, moving on to defining the AD test. Then I'll discuss the big difference between docs and code, which is the square root term. I'll follow that with a short discussion of the `n` term. 

### Variance of the difference of ECDFs

From the top, the value of an ECDF of data Y at a point X is distributed like a `binomial(n,p)` where `n` is the same as the size of the sample Y and `p` is given by `F_Y(X)` (the true CDF of Y at point X). Except that the ECDF is taking values between 0 and 1 and that binomial is taking values between 0 and N. Therefore, we need to divide the binomial distribution by `n` to get equivalence. The variance of a binomial is `np(1-p)`, the variance of our distribution becomes `p(1-p)/n` because dividing `n` out of the distribution pulls an `n^2` out of the variance. 

The difference between _two_ independent ECDFs (which under the null are from the same distribution) at that point X is pretty well behaved. In particular, the variance of the difference is `Var(X-Y) = Var(X)+Var(Y)-2Cov(X,Y) = Var(X)+Var(Y)`, (the second equality is from independence) and under the null `Var(X)=Var(Y)` so we get `Var(X-Y) = 2Var(X) = 2p(1-p)/n`. So in principle, the scaling factor we want is a relative of `2p(1-p)/n`.  I'll circle back to this in a minute. 

### Anderson Darling baseline

On the [Anderson-Darling Wikipedia page](https://en.wikipedia.org/wiki/Anderson–Darling_test), you'll see the formulation `(F_n(x)-F_n(x))^2/(F(x)(1-F(x))` [here F(x) is truth]. When you adapt this to a two sample test you get something like `(E_n(x)-F_n(x))^2/(G_n(x)(1-G_n(X))` [using G_n(x) to denote joint sample ecdfs]. In Anderson-Darling terms, the `p(1-p)` in our derived variance above is being replaced by the joint ECDF estimates, `G_n(x)(1-G_n(x))`. So far so good. 

### First error: Square root term not documented correctly

I'll start by examining the major difference between the code and the line above, the square root. As you noticed, my code has a `(G(1-G)^0.5` component. This is mostly a result of me letting the power we raise everything to vary. Under defaults for the AD test, everything will be squared in a minute (including the numerator `|E(x)-F(x)|`). After squaring (and still ignoring `n`), we have `|E-F|^2/(G(1-G))^0.5^2 = |E-F|^2/(G(1-G))`, which is the correct equation for the Anderson Darling test. This does differ from the docs, which dropped a square term in the numerator when defining AD. 

However, in the DTS test, the default is to use a power of 1. This makes the intuition of "a weighted integral of the difference" pretty straightforward (not that "weighted integral of squared difference" is much more complicated, but this was in part a choice driven by taste on my part).  That square root term will not be canceled out when the default is a power of 1. But, because the numerator is not being squared either, we need to think about what we want the scaling to be. Broadly, when we have a (centered) variable with a variance of 2, to convert it to unit variance, we divide out `sqrt(2)`, and that intuition extends to this setting pretty cleanly. Because the numerator is `|E(x)-F(x)|,` we want to divide out `sqrt(G(1-G))`, so the power of 0.5 is correct. Here too, I've screwed up the docs, which should show the DTS test stat as having a denominator with a square root in it.

### Second Error: `n` incorrectly used, inconsistently correcting, not documented

The second error is around the `sqrt(n)` term in the code. I want to be clear that this does not have any practical effect on performance. Each resample holds `n` fixed. Within each sum, an `n` factor is applied to every summand. So within each resample, this is scaling the entire test statistic by `1/sqrt(n)` or `1/n` depending on whether you're in the AD or DTS setting. It is not changing the weights differentially within a resample. And across resamples, it is applying the same rescaling term to every resampling. So it is not giving more or less weight to any particular sample possible under the null. (There are some resampling schemes where this wouldn't be true). On a fundamental level, you could drop the `n` term from the code entirely, and while all the test statistics you observe would be rescaled, your p-value would be unaffected. 

Why include it at all? Aesthetic reasons. One multiplication per loop won't materially affect speed, but including that `n` term means that we are (nearly) rescaling by the actual variance instead of by something proportional to the variance. But I made two mistakes. 1) it should be dividing out `n`, not multiplying it in. 2) I dropped the scalar 2 term, which we saw when we estimated the variance above. Properly, both the SD lines should read `sd = pow(2*gcur*(1-gcur)/n,0.5)`. Leaving this out of the docs was a deliberate simplification of the math in the docs, but perhaps silly -- because including it may have lead me to spot the errors there. In all likelihood, when I fix things up, I'll drop the `n` entirely, leaving `sd = pow(gcur*(1-gcur).0.5)`.


### Conclusion

I'm thrilled you've found the code and docs sufficiently helpful that you've examined them closely enough to find mistakes. Thank you for pointing them out to me! I will try to fix these issues soon. If you find more issues, please let me know.

I do not believe any of the code's actual errors (which do exist!) are material to any outcomes anyone may have observed. Neither you nor anyone else reading this needs to be concerned about results being invalid. The powers are undocumented (and that should be fixed) but correct, and the scaling by `n` _cannot_ affect results any more than multiplying all your data by 4 would. The docs definitely need some work (and contain genuine errors that may mislead people). I'm sort of continually displeased with them, and I will continue to update them. 

Please let me know if you still have questions. I'd also be happy to continue this conversation via email if that is easier (cdowd@chicagobooth.edu is currently best to reach me). And I would still love to see that python code.

**Comment by manorman5** [comment]
Thanks for the super thorough response! It definitely resolved my confusion. I've got one stats question that I'll follow up with over email. Yea, to be clear my question came from a place of not understanding the intuition behind the weight constructions rather than feeling like the weight construction compromised the metrics in any way. Given I was porting the code, I wanted to make sure there wasn't anything deeper I was missing. For what its worth, I found your code and its documentation to generally be super understandable and intuitive. 

I've attached my python code below. Let me know what bugs you find :) or if you have any questions. The code likely can be further optimized -- the tests work fast enough for my current purposes though, so I left the code as is. Feel free to follow up here or over email, whichever you prefer. Also, my `numba` version is `0.46.0` -- I'm not sure if the code works with other `numba` versions.

```
import sys

import numpy as np

from numba import njit, float64, int64, prange, config
import multiprocessing

import seaborn as sns
import matplotlib.pyplot as plt

config.NUMBA_NUM_THREADS = multiprocessing.cpu_count() - 1
config.THREADING_LAYER = 'safe'

def plot_diagnostics(data1, data2, data1_plot_kws, data2_plot_kws, outpath):
    """
    Visually compare two samples of data with a figure including the following
    plots:
        * Raw data distributions for each sample overlaid
        * ECDFs for each sample overlaid (ecdfs constructed using sample data)
            (This plot is to confirm ecdfs constructed for testing aren't wonky.)
        * ECDFs for each sample and their difference overlaid 
        * SD of Joint ECDF
    
    The figure is saved at `outpath`.

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.
    data1_plot_kws, data2_plot_kws : dict
        kwargs for plotting `data1` and `data2` respectively
    outpath : str or :class:`pathlib.Path`
        location to save diagnostic figure
    """
    joint_sample, ecdf1, ecdf2, ecdf_joint = _prep_test_inputs(data1.astype(np.float64), data2.astype(np.float64))
    fig = plt.figure(figsize=(45,15))
    gs = fig.add_gridspec(nrows=1, ncols=4)
    ax0 = fig.add_subplot(gs[0,0])
    ax1 = fig.add_subplot(gs[0,1])
    ax2 = fig.add_subplot(gs[0,2])
    ax3 = fig.add_subplot(gs[0,3])
    ax1.set_title("Basic ECDFs")
    ax1.plot(np.sort(data1), (np.arange(1, (data1.shape[0] + 1))/ data1.shape[0]), **data1_plot_kws)
    ax1.plot(np.sort(data2), (np.arange(1, (data2.shape[0] + 1))/ data2.shape[0]), **data2_plot_kws)
    lg1 = ax1.legend(loc="upper left")
    ax2.set_title("Test ECDFs")
    ax2.plot(joint_sample, ecdf1, **data1_plot_kws)
    ax2.plot(joint_sample, ecdf2, **data2_plot_kws)
    ax2.plot(joint_sample, ecdf1 - ecdf2, color="black", label="Difference", zorder=100)
    ymin, ymax = ax1.get_ylim()
    ax2.set_ylim(-ymax, ymax)
    lg2 = ax2.legend(loc="upper left")
    ax3.set_title("SD of Joint ECDF")
    sds = _sds(ecdf_joint)
    ax3.plot(joint_sample, sds, color="black")
    ax0.set_title("Raw Distributions")
    sns.distplot(data1, ax=ax0, kde=False, hist_kws = data1_plot_kws)
    sns.distplot(data2, ax=ax0, kde=False, hist_kws = data2_plot_kws)
    lg0 = ax0.legend(loc="upper right")
    fig.savefig(outpath)
    plt.close('all')

def twosample_default_test(data1, data2, default_test_name = "dts"):
    """
    Two sample testing using permutation. This function calculates
    a distance metric between two samples of data and then constructs
    a pvalue for that distance metric using permutation.

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.
    default_test_name : str
        Name of distance metric available by default. Options include:
        * `ks` (Kolmogorov-Smirnov)
        * `kuiper`
        * `ad` (Anderson-Darling)
        * `cvm` (Cramer-Von Mises)
        * `wass` (Wasserstein)
        * `dts`
    
    Returns:
    --------
    float, float
        distance metric, p-value
    """
    test = getattr(sys.modules[__name__], f"_{default_test_name}")
    return twosample_test(data1, data2, test)

@njit(parallel=True)
def twosample_test(data1, data2, test, nboots=10000):
    """
    Two sample testing using permutation. This function calculates
    a distance metric between two samples of data and then constructs
    a pvalue for that distance metric using permutation.

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.
    test : func
        function that takes `data1` and `data2` as inputs and calculates a distance 
        metric comparing the two samples. `test` must be njitified.
    nboots : int
        Number of permutations to use to generate the pvalue
    
    Returns:
    --------
    float, float
        distance metric, p-value
    """
    # type conversion so njitified functions don't get upset
    data1, data2 = data1.astype(np.float64), data2.astype(np.float64)

    # create distance metric
    stat = test(data1, data2)

    # generate pvalue
    stat_boots = np.zeros(nboots, dtype=np.float64)
    joint_sample = np.concatenate((data1, data2))
    for ii in prange(nboots):
        stat_boots[ii] = test(
            joint_sample[np.random.randint(0, joint_sample.shape[0], data1.shape[0])], 
            joint_sample[np.random.randint(0, joint_sample.shape[0], data2.shape[0])]
        )
    pvalue = np.sum(stat_boots >= stat) / nboots

    return stat, pvalue


##############################################################################
# Helper functions for default tests
##############################################################################

@njit("UniTuple(float64[::1],4)(float64[::1],float64[::1])",cache=True)
def _prep_test_inputs(data1, data2):
    """
    Construct arrays necessary for default tests

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.

    Returns:
    --------
    (array_like, array_like, array_like, array_like)
        Four element tuple of 1-Dimensional arrays. The first array is 
        the joint sample of `data1` and `data2` sorted in ascending order. The
        other three arrays are the ECDFs of `data1`, `data2` and the joint sample,
        respectively.
    """
    data1 = np.sort(data1.astype(np.float64))
    data2 = np.sort(data2.astype(np.float64))
    joint_sample = np.sort(np.concatenate((data1, data2)))

    # use searchsorted to account for differences in data* sizes
    ecdf1 = np.searchsorted(data1, joint_sample, side="right") / data1.shape[0]
    ecdf2 = np.searchsorted(data2, joint_sample, side="right") / data2.shape[0]
    ecdf_joint = np.arange(1, joint_sample.shape[0] + 1) / joint_sample.shape[0]

    return joint_sample, ecdf1, ecdf2, ecdf_joint

@njit("int64[:](float64[::1])", cache=True)
def _duplicated(a):
    """
    Find array indices of the last appearance of an element in an array.

    Parameters:
    -----------
    a : array_like, 1-Dimensional
        Array should be sorted in ascending order
    
    Returns:
    --------
    array_like, 1-Dimensional
        indices of `a` 
    """
    return np.nonzero(np.diff(a))[0]

@njit("float64[::1](float64[::1])",cache=True)
def _sds(ecdf):
    """
    Construct standard deviation of an ECDF
    at every x.

    Parameters:
    -----------
    ecdf : array_like, 1-Dimensional
        Array values must be between 0 and 1.
    
    Returns:
    --------
    array_like, 1-Dimensional
        standard deviation of `ecdf` at every x
    """
    return np.sqrt(ecdf * (1 - ecdf))

@njit("float64[::1](float64[::1])", cache=True)
def _widths(a):
    """
    Construct an array of differences where the difference for index 
    i = a[i+1] - a[i].

    Parameters:
    -----------
    a : array_like, 1-Dimensional
        values to difference

    Returns:
    --------
    array_like, 1-Dimensional
    """
    return np.diff(a)

@njit("float64[::1](float64[::1], float64[::1], float64[::1])", cache=True)
def _weighted_diffs(ecdf1, ecdf2, ecdf_joint):
    """
    Calculate the differences between two samples' ecdfs and weight those
    differences using the standard deviations of the two sample's joint distribution's
    ecdf.

    Parameters:
    -----------
    ecdf1, ecdf2, ecdf_joint : array_like, 1-Dimensional
        Ecdfs of sample 1, sample 2, and the joint distribution of sample 1 and 2, respectively

    Returns:
    --------
    array_like, 1-Dimensional
        The differences between `ecdf1` and `ecdf2` weighted using the 
        standard deviations of `ecdf_joint`.
    """

    # calculcate standard deviations G(x) at every x
    # replacing zeroes with nans to avoid divide by zero case
    sds = _sds(ecdf_joint)
    sds[sds == 0] = np.nan

    # apply weight to differences
    # replace nans with zeroes to get a valid
    # sum later down pipeline
    weighted_diffs = np.abs(ecdf1 - ecdf2) / sds
    weighted_diffs[np.isnan(weighted_diffs)] = 0

    return weighted_diffs

##############################################################################
# Defaults tests
##############################################################################
@njit("float64(float64[::1],float64[::1])",cache=True)
def _ks(data1, data2):
    r"""
    Compute the Kolmogorov-Smirnov distance metric between 
    `data1` and `data2`.

    Let E be the ECDF of `data1`, F bet the ECDF of `data2`.
    :math:ks = \max_{x \in X}\abs{E(x) - F(x)}

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.

    Returns:
    --------
    float
        Komogrov-Smirnov distance metric computed using `data1` and `data2`
    """
    joint_sample, ecdf1, ecdf2, ecdf_joint = _prep_test_inputs(data1, data2)
    return np.max(np.abs(ecdf1 - ecdf2))

@njit("float64(float64[::1],float64[::1])",cache=True)
def _kuiper(data1, data2):
    r"""
    Compute the Kuiper distance metric between 
    `data1` and `data2`.

    Let E be the ECDF of `data1` and F be the ECDF of `data2`.
    :math:kuiper = \abs{\max_{x \in X}(E(x) - F(x))} + \abs{\min_{x \in X}(E(x) - F(x))}

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.

    Returns:
    --------
    float
        Kuiper distance metric computed using `data1` and `data2`
    """
    joint_sample, ecdf1, ecdf2, ecdf_joint = _prep_test_inputs(data1, data2)
    ecdfdiffs = ecdf1 - ecdf2
    return np.abs(np.max(ecdfdiffs)) + np.abs(np.min(ecdfdiffs))

@njit("float64(float64[::1],float64[::1])",cache=True)
def _cvm(data1, data2):
    r"""
    Compute the Cramer-Von Mises distance metric between 
    `data1` and `data2`.

    Let E be the ECDF of `data1` and F bet the ECDF of `data2`.
    :math:CVM = \sum_{x \in X}\abs{E(x) - F(x)}^2

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.

    Returns:
    --------
    float
        Cramer-Von Mises distance metric computed using `data1` and `data2`
    """
    joint_sample, ecdf1, ecdf2, ecdf_joint = _prep_test_inputs(data1, data2)
    ii = _duplicated(joint_sample)
    return np.sum(
        np.abs(
            ecdf1[ii] - ecdf2[ii]
        )**2
    )
    
@njit("float64(float64[::1],float64[::1])",cache=True)
def _ad(data1, data2):
    r"""
    Compute the Anderson-Darling distance metric between 
    `data1` and `data2`.

    Let E be the ECDF of `data1`, F bet the ECDF of `data2`, and
    G be the ECDF of the joint distribution of `data1` and `data2`.
    :math:AD = \sum_{x \in X}\frac{\abs{E(x) - F(x)}^2}{(G(x)*(1-G(x))}

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.

    Returns:
    --------
    float
        Anderson-Darling distance metric computed using `data1` and `data2`
    """
    joint_sample, ecdf1, ecdf2, ecdf_joint = _prep_test_inputs(data1, data2)
    ii = _duplicated(joint_sample)
    # create weighted differences where weights
    # are the standard deviations of G(x)
    weighted_diffs = _weighted_diffs(ecdf1, ecdf2, ecdf_joint)
    return np.sum(weighted_diffs[ii]**2)

@njit("float64(float64[::1],float64[::1])",cache=True)
def _wass(data1, data2):
    r"""
    Compute the Wasserstein distance metric between 
    `data1` and `data2`.

    Let E be the ECDF of `data1`, F bet the ECDF of `data2`, and
    G be the ECDF of the joint distribution of `data1` and `data2`.
    :math:wass = \int_{-\infty}^{\infty}\abs{E(x) - F(x)}\,dx

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.

    Returns:
    --------
    float
        Wasserstein distance metric computed using `data1` and `data2`
    """
    joint_sample, ecdf1, ecdf2, ecdf_joint = _prep_test_inputs(data1, data2)
    widths = _widths(joint_sample)
    # dropping last obs of both ecdfs b/c should be one for both
    # and length of widths is one less than the length of both ecdfs
    return np.sum(np.abs(ecdf1 - ecdf2)[:-1] * widths)

@njit("float64(float64[::1],float64[::1])",cache=True)
def _dts(data1, data2):
    r"""
    Compute the DTS distance metric between 
    `data1` and `data2`.

    Let E be the ECDF of `data1`, F bet the ECDF of `data2`, and
    G be the ECDF of the joint distribution of `data1` and `data2`.
    :math:DTS = \int_{-\infty}^{\infty}\frac{\abs{E(x) - F(x)}}{\sqrt{G(x)*(1-G(x))}}\,dx

    Parameters:
    -----------
    data1, data2 : array_like, 1-Dimensional
        Two arrays of sample observations, sample sizes can be different.

    Returns:
    --------
    float
        DTS distance metric computed using `data1` and `data2`
    """
    joint_sample, ecdf1, ecdf2, ecdf_joint = _prep_test_inputs(data1, data2)
    widths = _widths(joint_sample)
    # create weighted differences where weights
    # are the standard deviations of G(x)
    weighted_diffs = _weighted_diffs(ecdf1, ecdf2, ecdf_joint)

    # dropping last ob of both weighted diffs b/c should be zero
    # and length of widths is one less than the length of weighted diffs
    return np.sum(weighted_diffs[:-1] * widths)
```

**Comment by cdowd** [comment]
Appreciate your python code (should have said it sooner) -- will email you about that. 

I've released an updated package which addresses this concern. planning to close this issue now.
